[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"
  base = "floc26website"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20.11.1"
  PRISMA_TELEMETRY_INFORMATION = "e2e-test"
  PRISMA_CLI_QUERY_ENGINE_TYPE = "binary"
  PRISMA_CLIENT_ENGINE_TYPE = "binary"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[[build.processing]]
  skip_processing = false

[[build.processing.css]]
  bundle = true
  minify = true

[[build.processing.js]]
  bundle = true
  minify = true

[[build.processing.html]]
  pretty_urls = true

[[build.processing.images]]
  compress = true 