import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = Poppins({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ['400']
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
