
// No need for PLACEHOLDER_IMAGE import if using null

export const committeeData = {
  organizers: [
    { name: 'Rajeev Alur', image: "https://www.cis.upenn.edu/~alur/RA24.jpg", affiliation: 'University of Pennsylvania', role: 'General Chair', webpage: 'https://www.cis.upenn.edu/~alur/' },
    { name: 'Alexandra Silva', image: "https://alexandrasilva.org/images/profile.jpeg", affiliation: 'Cornell University', role: 'Advisory Chair', webpage: 'https://alexandrasilva.org' },
    { name: 'Nuno P. Lopes', image: "https://web.ist.utl.pt/nuno.lopes/photo.jpg", affiliation: 'University of Lisbon', role: 'Organization Chair', webpage: 'https://web.ist.utl.pt/nuno.lopes/' },
    { name: 'Aws Albarghouthi', image: "https://pages.cs.wisc.edu/~aws/photo2018.jpg", affiliation: 'UW-Madison', role: 'Fundraising Co-Chair', webpage: 'https://pages.cs.wisc.edu/~aws/' },
    { name: 'Jules Villard', image: "https://jvillard.net/moi2.jpg", affiliation: 'Meta', role: 'Fundraising Co-Chair', webpage: 'https://jvillard.net' },
    { name: 'Loris D\'Antoni', image: "https://cseweb.ucsd.edu/~ldantoni/images/face.jpg", affiliation: 'UC San Diego', role: 'Fundraising Co-Chair', webpage: 'https://cseweb.ucsd.edu/~ldantoni/' },
    { name: 'Alessandro Gianola', image: "https://arsr.inesc-id.pt/~agianola/AlessandroGianola.jpg", affiliation: 'University of Lisbon', role: 'Workshops Co-Chair', webpage: 'https://arsr.inesc-id.pt/~agianola/' },
    { name: 'Bernd Finkbeiner', image: null, "https://finkbeiner.groups.cispa.de/img/profile/Bernd_Finkbeiner.avif": 'CISPA Helmholtz Center for Information Security', role: 'Workshops Co-Chair', webpage: 'https://finkbeiner.groups.cispa.de/people/finkbeiner.html' },
    { name: 'José Fragoso Santos', image: "https://web.ist.utl.pt/jose.fragoso/images/Jose.png", affiliation: 'University of Lisbon', role: 'Volunteers Chair', webpage: 'https://web.ist.utl.pt/jose.fragoso/' },
    { name: 'Caterina Urban', image: null, affiliation: 'INRIA / ENS', role: 'Publicity Chair', webpage: 'https://caterinaurban.github.io' },
  ],
  conferenceCommittees: [
    { name: 'Philipp Ruemmer', image: "http://www.philipp.ruemmer.org/portrait.jpeg", affiliation: 'University of Regensburg', role: 'CAV Conference Chair', webpage: 'http://www.philipp.ruemmer.org' },
    { name: 'Inês Lynce', image: "https://sat.inesc-id.pt/~ines/ines-lynce-jul23-short-face.jpg", affiliation: 'University of Lisbon', role: 'CP Conference Chair', webpage: 'https://sat.inesc-id.pt/~ines/' },
    { name: 'Pedro Adão', image: "https://www.math.tecnico.ulisboa.pt/~padao/IMG_1652-web.jpg", affiliation: 'University of Lisbon', role: 'CSF Conference Chair', webpage: 'https://www.math.tecnico.ulisboa.pt/~padao/' },
    { name: 'Matthias Knorr', image: null, affiliation: 'NOVA University Lisbon', role: 'DL Conference Chair', webpage: 'https://userweb.fct.unl.pt/~mkn/' },
    { name: 'Sandra Alves', image: "https://www.dcc.fc.up.pt/~sandra/Home/Home_files/Photo.jpg", affiliation: 'University of Porto', role: 'FSCD Conference Chair', webpage: 'https://www.dcc.fc.up.pt/~sandra/Home/Home.html' },
    { name: 'Vítor Santos Costa', image: null, affiliation: 'University of Porto', role: 'ICLP Conference Chair', webpage: 'https://www.dcc.fc.up.pt/~vsc/' },
    { name: 'Carlos Caleiro', image: "https://sqigmath.tecnico.ulisboa.pt/photos/ccal.png", affiliation: 'University of Lisbon', role: 'IJCAR Conference Chair', webpage: 'https://sqig.math.tecnico.ulisboa.pt/ccal' },
    { name: 'João F. Ferreira', image: "https://joaoff.com/authors/jff/avatar_hu91756166fdcda866b2836c864cc3667a_424014_270x270_fill_q90_lanczos_center.jpg", affiliation: 'University of Lisbon', role: 'ITP Conference Chair', webpage: 'https://joaoff.com' },
    { name: 'João Leite', image: "https://userweb.fct.unl.pt/~jleite/images/jleite.jpg", affiliation: 'NOVA University Lisbon', role: 'KR Conference Chair', webpage: 'https://userweb.fct.unl.pt/~jleite/' },
    { name: 'Bernardo Toninho', image: "https://web.tecnico.ulisboa.pt/bernardo.toninho/images/me.jpg", affiliation: 'University of Lisbon', role: 'LICS Conference Chair', webpage: 'https://web.tecnico.ulisboa.pt/bernardo.toninho/' },
    { name: 'Ricardo Gonçalves', image: "https://userweb.fct.unl.pt/~rjrg/images/ricardo.jpg", affiliation: 'NOVA University Lisbon', role: 'NMR Conference Chair', webpage: 'https://userweb.fct.unl.pt/~rjrg/' },
    { name: 'Vasco Manquinho', image: null, affiliation: 'University of Lisbon', role: 'SAT Conference Chair', webpage: 'https://sat.inesc-id.pt/~vmm/' },
  ],
  programCommittees: [
    { name: 'Anthony W. Lin', image: "https://anthonywlin.github.io/anthony-talk.jpg", affiliation: 'Technical University of Kaiserslautern', role: 'CAV PC Chair', webpage: 'https://anthonywlin.github.io' },
    { name: 'Eva Darulova', image: "https://malyzajko.github.io/images/profile-2023-up.jpg", affiliation: 'Uppsala University', role: 'CAV PC Chair', webpage: 'https://malyzajko.github.io' },
    { name: 'Philipp Ruemmer', image: "http://www.philipp.ruemmer.org/portrait.jpeg", affiliation: 'University of Regensburg', role: 'CAV PC Chair', webpage: 'http://www.philipp.ruemmer.org' },
    { name: 'Frank Pfenning', image: "https://www.cs.cmu.edu/~fp/fp-small.jpg", affiliation: 'CMU', role: 'FSCD PC Chair', webpage: 'https://www.cs.cmu.edu/~fp/' },
    { name: 'Laura Giordano', image: "http://people.unipmn.it/laura.giordano/f_laura_2019", affiliation: 'Università del Piemonte Orientale', role: 'ICLP PC Chair', webpage: 'https://people.unipmn.it/laura.giordano/' },
    { name: 'Armin Biere', image: "https://cca.informatik.uni-freiburg.de/img/biere.jpg", affiliation: 'University of Freiburg', role: 'IJCAR PC Chair', webpage: 'https://cca.informatik.uni-freiburg.de/biere/' },
    { name: 'Carsten Lutz', image: "https://home.uni-leipzig.de/clu/imgs/hamid1.jpg", affiliation: 'Universität Leipzig', role: 'IJCAR PC Chair', webpage: 'https://home.uni-leipzig.de/clu/' },
    { name: 'Sara Negri', image: "https://lh4.googleusercontent.com/2zZJGey7nrlVnR5CFYEHBYDGE_NM3UYuO4iEEjpkRPk7ZGZMZ7KMxLiSxWicy1bcRdq-Baak4lnpSROxfI7o2ncrpxjs_y44Nw0GmSF5OR6jon1lML1Bvxyl0KO9jVS-kw=w1280", affiliation: 'Università degli Studi di Genova', role: 'IJCAR PC Chair', webpage: 'https://sites.google.com/view/saranegri/home' },
    { name: 'Ekaterina Komendantskaya', image: "https://www.macs.hw.ac.uk/~ek19/KK2.png", affiliation: 'Heriot-Watt University and University of Southampton', role: 'ITP PC Chair', webpage: 'https://www.macs.hw.ac.uk/~ek19/' },
    { name: 'Tobias Nipkow', image: "https://www21.in.tum.de/~nipkow/ich2019.jpg", affiliation: 'TU Munich', role: 'ITP PC Chair', webpage: 'https://www21.in.tum.de/~nipkow/' },
    { name: 'Franz Baader', image: "https://tu-dresden.de/ing/informatik/thi/lat/ressourcen/bilder/fotos-von-mitarbeitern/franz_baader_wide.jpg/@@images/1f01cc66-e39a-459c-8165-234c7713b4be.jpeg", affiliation: 'TU Dresden', role: 'KR PC Chair', webpage: 'https://tu-dresden.de/ing/informatik/thi/lat/die-professur/franz-baader' },
    { name: 'Marie-Laure Mugnier', image: "https://www.lirmm.fr/~mugnier/index_files/mlm.jpg", affiliation: 'University of Montpellier', role: 'KR PC Chair', webpage: 'https://www.lirmm.fr/~mugnier/' },
    { name: 'Claudia Faggian', image: null, affiliation: 'CNRS', role: 'LICS PC Chair', webpage: 'https://www.irif.fr/~faggian/' },
    { name: 'Joost-Pieter Katoen', image: "https://www-i2.informatik.rwth-aachen.de/~katoen/newglasses.jpg", affiliation: 'RWTH Aachen University', role: 'LICS PC Chair', webpage: 'https://www-i2.informatik.rwth-aachen.de/~katoen/' },
    { name: 'Alexey Ignatiev', image: "https://alexeyignatiev.github.io/assets/img/me.jpg", affiliation: 'Monash University', role: 'SAT PC Chair', webpage: 'https://alexeyignatiev.github.io' },
    { name: 'Stefan Szeider', image: "https://www.ac.tuwien.ac.at/wp/wp-content/uploads/szeider-blackboard-1536x720.jpeg", affiliation: 'TU Wien', role: 'SAT PC Chair', webpage: 'https://www.ac.tuwien.ac.at/people/szeider/' },
  ],
  steeringCommittee: [
    { name: 'Rajeev Alur', image: "https://www.cis.upenn.edu/~alur/RA24.jpg", affiliation: 'University of Pennsylvania', role: 'General Chair', webpage: 'https://www.cis.upenn.edu/~alur/' },
    { name: 'Alexandra Silva', image: "https://alexandrasilva.org/images/profile.jpeg", affiliation: 'Cornell University', role: 'Advisory Chair', webpage: 'https://alexandrasilva.org' },
    { name: 'Daniel Kröning', image: "https://www.kroening.com/photo_neu.jpg", affiliation: 'University of Oxford', role: 'CAV Representative', webpage: 'https://www.kroening.com' },
    { name: 'Hélène Verhaeghe', image: "https://hverhaeghe.bitbucket.io/images/me.jpg", affiliation: 'KU Leuven', role: 'CP Representative', webpage: 'https://hverhaeghe.bitbucket.io' },
    { name: 'Dominique Unruh', image: "https://kodu.ut.ee/~unruh/portrait-200.jpg", affiliation: 'University of Tartu', role: 'CSF Representative', webpage: 'https://kodu.ut.ee/~unruh/' },
    { name: 'Patrick Baillot', image: "https://pro.univ-lille.fr/fileadmin/_processed_/1/8/csm_DSC_0862_9c3cca34f8.jpg", affiliation: 'CNRS/Université de Lille', role: 'FSCD Representative', webpage: 'https://pro.univ-lille.fr/patrick-baillot/' },
    { name: 'Marco Gavanelli', image: "https://servizi.unife.it/foto/gvnmrc.jpg", affiliation: 'Università degli Studi di Ferrara', role: 'ICLP Representative', webpage: 'https://docente.unife.it/docenti-en/marco.gavanelli?set%5Flanguage=en' },
    { name: 'Franz Baader', image: "https://tu-dresden.de/ing/informatik/thi/lat/ressourcen/bilder/fotos-von-mitarbeitern/franz_baader_wide.jpg/@@images/1f01cc66-e39a-459c-8165-234c7713b4be.jpeg", affiliation: 'TU Dresden', role: 'IJCAR Representative', webpage: 'https://tu-dresden.de/ing/informatik/thi/lat/die-professur/franz-baader' },
    { name: 'Magnus Myreen', image: "https://www.cse.chalmers.se/~myreen/me.jpg", affiliation: 'Chalmers University', role: 'ITP Representative', webpage: 'https://www.cse.chalmers.se/~myreen/' },
    { name: 'Esra Erdem', image: "https://people.sabanciuniv.edu/esraerdem/esra15.jpg", affiliation: 'Sabanci University', role: 'KR Representative', webpage: 'https://people.sabanciuniv.edu/esraerdem/' },
    { name: 'Igor Walukiewicz', image: null, affiliation: 'University of Bordeaux', role: 'LICS Representative', webpage: 'https://www.labri.fr/perso/igw/' },
    { name: 'Matthias Thimm', image: "https://www.mthimm.de/images/mt2021.jpg", affiliation: 'FernUniversität in Hagen', role: 'NMR Representative', webpage: 'https://www.mthimm.de' },
    { name: 'Armin Biere', image: "https://cca.informatik.uni-freiburg.de/img/biere.jpg", affiliation: 'University of Freiburg', role: 'SAT Representative', webpage: 'https://cca.informatik.uni-freiburg.de/biere/' },
  ],
};